name: Run Selenium Tests and Deploy Allure Report

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

      - name: Download Allure commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xvzf allure-2.27.0.tgz
          echo "ALLURE_HOME=$(pwd)/allure-2.27.0/bin" >> $GITHUB_ENV

      - name: Copy previous history
        run: |
          git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          mkdir -p target/allure-results/history
          cp -R gh-pages/history target/allure-results || echo "No history to copy"

      - name: Generate Allure Report
        run: |
          ${{ env.ALLURE_HOME }}/allure generate target/allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        run: |
          cd allure-report
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy Allure report to GitHub Pages"
          git push --force origin gh-pages
